# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: foundry-hybrid-private
metadata:
  template: foundry-samples/19-hybrid-private-resources-agent-setup
infra:
  provider: bicep
  path: .
  module: main
